plugins {
    id 'application'
}

group = 'replayroom'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'replayroom.Main'
}

tasks.named('run') {
    standardInput = System.in
}

tasks.named('test') {
    testClassesDirs = sourceSets.test.output.classesDirs
    classpath = sourceSets.test.runtimeClasspath
    dependsOn tasks.named('compileTestJava')
    doLast {
        javaexec {
            classpath = sourceSets.test.runtimeClasspath
            mainClass = 'replayroom.AllTests'
        }
    }
}
